### ISSUE TITLE
sockstat (ss)

### ISSUE THREAD

**Issue by ldrahnik** [nesfit/ISA#1]
https://github.com/nesfit/ISA/blob/e2c07a5d2f1710ac1ad1a04e1e358c3663655521/wireshark/theory.tex#L92

Pozměnil bych část s **sockstat (ss)**. Už přesně nevím co mi vyskočilo po zadání `sockstat` (předpokládám `sockstat: command not found`, ale nepochopil jsem závorku s `ss`. `sockstat` na distribuci Linuxu v laboratoři není. Je to podle mého názoru matoucí. Například na Debianu by vyskočilo `sudo apt install sockstat` pokud by již nebyl přidán.

**Comment by kjerabek** [comment]
Prohodil jsem to, příkaz ss je onen příkaz pro sockstat.
